dependencies:
  - name: rabbitmq
    version: 5.5.0
    repository: "https://kubernetes-charts.storage.googleapis.com"
    condition: rabbitmq.enabled
  - name: postgresql
    version: 3.18.3
    repository: "https://kubernetes-charts.storage.googleapis.com"
    condition: postgresql.enabled
  - name: redis
    version: 7.0.0
    repository: "https://kubernetes-charts.storage.googleapis.com"
    condition: redis.enabled
  - name: gateway
    version: 1.0.0
    repository: "file://../services/gateway/chart"
    condition: gateway.enabled
  - name: auth-service
    version: 1.0.0
    repository: "file://../services/auth-service/chart"
    condition: auth-service.enabled
  - name: cart-service
      version: 1.0.0
      repository: "file://../services/cart-service/chart"
      condition: cart-service.enabled
  - name: deposit-service
      version: 1.0.0
      repository: "file://../services/deposit-service/chart"
      condition: deposit-service.enabled
  - name: order-service
      version: 1.0.0
      repository: "file://../services/order-service/chart"
      condition: order-service.enabled
