rabbitmq:
  enabled: true
  fullnameOverride: "rabbitmq"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  rabbitmq:
    existingPasswordSecret: "rabbitmq"
    existingErlangSecret: "rabbitmq"

postgresql:
  image:
    tag: "10.7.0-r68"
  enabled: true
  fullnameOverride: "postgres"
  existingSecret: "postgres"

redis:
  enabled: true
  fullnameOverride: "redis"

gateway:
  enabled: true

auth-service:
  enabled: true

cart-service:
  enabled: true

deposit-service:
  enabled: true

order-service:
  enabled: true

product-service:
  enabled: true
