rabbitmq:
  enabled: true
  fullnameOverride: "rabbitmq"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

postgresql:
  enabled: true
  fullnameOverride: "postgres"

redis:
  enabled: true
  fullnameOverride: "redis"

gateway:
  enabled: true

auth-service:
  enabled: true

cart-service:
  enabled: true

deposit-service:
  enabled: true

order-service:
  enabled: true

product-service:
  enabled: true
