rabbitmq:
  enabled: true
  fullnameOverride: "rabbitmq"

postgresql:
  enabled: true
  fullnameOverride: "postgres"
  replication:
    enabled: true
    slaveReplicas: 3

redis:
  enabled: true
  fullnameOverride: "redis"

gateway:
  enabled: true

auth-service:
  enabled: true

cart-service:
  enabled: true

deposit-service:
  enabled: true

order-service:
  enabled: true
