image: registry.gitlab.com/typokign/microservices/ci:latest

services:
  - docker:dind

stages:
  - lint
  - build
  - deploy

lint:
  stage: lint
  script:
    - make lint

build gateway:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker pull registry.gitlab.com/typokign/microservices/gateway || true
    - docker build --cache-from registry.gitlab.com/typokign/microservices/gateway -t registry.gitlab.com/typokign/microservices/gateway:${CI_COMMIT_SHA:0:8} services/gateway
    - docker push registry.gitlab.com/typokign/microservices/gateway:${CI_COMMIT_SHA:0:8}

#build auth-service:
#  stage: build
#
#build cart-service:
#  stage: build
#
#build deposit-service:
#  stage: build

.functions: &functions |
  function init_helm() {
    echo ${KUBECONFIG} >> ~/.kube/config
    helm init --tiller-namespace kube-system --upgrade --wait
  }

deploy:
  stage: deploy
  image: devth/helm
  before_script:
    - *functions
  script:
    - init_helm
    - helm upgrade --install --wait --namespace ${CI_COMMIT_REF_NAME} ${CI_COMMIT_REF_NAME} ./chart
