image: registry.gitlab.com/typokign/microservices/ci:latest

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - lint
  - build
  - deploy

lint:
  stage: lint
  script:
    - make lint

build gateway:
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull registry.gitlab.com/typokign/microservices/gateway || true
    - docker build --cache-from registry.gitlab.com/typokign/microservices/gateway -t registry.gitlab.com/typokign/microservices/gateway:${CI_COMMIT_SHORT_SHA} services/gateway
    - docker push registry.gitlab.com/typokign/microservices/gateway:${CI_COMMIT_SHORT_SHA}

#build auth-service:
#  stage: build
#
#build cart-service:
#  stage: build
#
#build deposit-service:
#  stage: build

.functions: &functions |
  function init_helm() {
    echo "$KUBECONFIG" >> ./kubeconfig
    helm init --tiller-namespace kube-system --kubeconfig ./kubeconfig --upgrade --wait
  }

deploy:
  stage: deploy
  image: devth/helm
  before_script:
    - *functions
  script:
    - init_helm
    - helm upgrade --install --wait --namespace $CI_COMMIT_REF_NAME \
        --set gateway.image.tag="${CI_COMMIT_SHORT_SHA}" \
        --set auth-service.image.tag="${CI_COMMIT_SHORT_SHA}"
        --set cart-service.image.tag="${CI_COMMIT_SHORT_SHA}" \
        --set deposit-service.image.tag="${CI_COMMIT_SHORT_SHA}" \
        --set order-service.image.tag="${CI_COMMIT_SHORT_SHA}" \
        $CI_COMMIT_REF_NAME ./chart
