version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "127.0.0.1:5672:5672"
  postgres:
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  gateway:
    image: tictactoeteam/gateway
    build:
      context: ./services/gateway/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
  auth-service:
    image: tictactoeteam/auth-service
    build:
      context: ./services/auth-service/
      dockerfile: Dockerfile
  product-service:
    image: tictactoeteam/product-service
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
  cart-service:
    image: tictactoeteam/cart-service
    build:
      context: ./services/cart-service/
      dockerfile: Dockerfile
  deposit-service:
    image: tictactoeteam/deposit-service
    build:
      context: ./services/deposit-service/
      dockerfile: Dockerfile
  order-service:
    image: tictactoeteam/order-service
    build:
      context: ./services/order-service/
      dockerfile: Dockerfile

