version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 1s
      timeout: 1s
      retries: 15
  postgres:
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
  redis-master:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  auth-service:
    image: registry.gitlab.com/typokign/microservices/auth-service
    build:
      context: ./services/auth-service/
      dockerfile: Dockerfile
    environment:
      DO_INIT: "true"
      POSTGRES_URL: "jdbc:postgresql://postgres:5432/auth"
      POSTGRES_USER: "auth"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_SU_URL: "jdbc:postgresql://postgres:5432/"
      POSTGRES_SUPERUSER: "postgres"
      POSTGRES_SU_PASSWORD: "postgres"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "guest"
    volumes:
      - "./services/auth-service/cert.pem:/opt/cert.pem"
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgres

  cart-service:
    image: registry.gitlab.com/typokign/microservices/cart-service
    build:
      context: ./services/cart-service/
      dockerfile: Dockerfile
    environment:
      REDIS_PASSWORD: ""
    volumes:
      - "./services/auth-service/pub.pem:/opt/pub.pem"
    depends_on:
      - redis-master

  deposit-service:
    image: registry.gitlab.com/typokign/microservices/deposit-service
    build:
      context: ./services/deposit-service/
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - rabbitmq
      - redis-master

  order-service:
    image: registry.gitlab.com/typokign/microservices/order-service
    build:
      context: ./services/order-service/
      dockerfile: Dockerfile
    environment:
      DO_INIT: "true"
      POSTGRES_URL: "jdbc:postgresql://postgres:5432/order_service"
      POSTGRES_USER: "order_service"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_SU_URL: "jdbc:postgresql://postgres:5432/"
      POSTGRES_SUPERUSER: "postgres"
      POSTGRES_SU_PASSWORD: "postgres"
    volumes:
      - "./services/auth-service/cert.pem:/opt/cert.pem"

  product-service:
    image: registry.gitlab.com/typokign/microservices/product-service
    build:
      context: ./services/product-service
      dockerfile: Dockerfile

  gateway:
    image: registry.gitlab.com/typokign/microservices/gateway
    build:
      context: ./services/gateway/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - auth-service
      - cart-service
      - deposit-service
      - order-service
      - product-service
