apiVersion: v1
kind: Secret
metadata:
  name: "auth-service"
type: Opaque
stringData:
  postgresUrl: "jdbc:postgresql://postgres:5432/auth"
  postgresSuperuser: "postgres"
  postgresSuperuserUrl: "jdbc:postgresql://postgres:5432/"
  postgresUser: "auth"
  postgresPassword: "NxkQ7Lb4QoddHS0YDZvrFGF7bcFzjqUa"

---
apiVersion: v1
kind: Secret
metadata:
  name: "product-service"
type: Opaque
stringData:
  postgresUrl: "jdbc:postgresql://postgres:5432/product"
  postgresSuperuser: "postgres"
  postgresSuperuserUrl: "jdbc:postgresql://postgres:5432/"
  postgresUser: "product"
  postgresPassword: "otc9nDRf37zj47aFsNTKxxbEoi0Wi0g9"

---
apiVersion: v1
kind: Secret
metadata:
  name: "order-service"
type: Opaque
stringData:
  postgresUrl: "jdbc:postgresql://postgres:5432/order_service"
  postgresSuperuser: "postgres"
  postgresSuperuserUrl: "jdbc:postgresql://postgres:5432/"
  postgresUser: "order_service"
  postgresPassword: "aN3Em4U3ieScJLMBpqPwyBl0Fw40vhDA"

---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres"
type: Opaque
stringData:
  postgresql-password: "nzuehwXRzUOrVi7wF2mPAAsTlpK9WRB3CSw2cnlIan"
  postgresql-replication-password: "4pdUZ4AmjyryUHcwK3PPrBLe0nKq3BZdBQj6IroIP0"

---
apiVersion: v1
kind: Secret
metadata:
  name: "jwt"
type: Opaque
stringData:
  private: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgD35s3D/elczlxxKy
    OGyr6dottRgQbmgyvV81rzqh3BihRANCAAQHa0wBis62okqYeDme+a5sAp94MDo+
    jPWd1qyhFEd3ENrLhOvdYDzat2IxTEXhAbtNNxTOCbn6tgswV1rGaXAy
    -----END PRIVATE KEY-----
  public: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEB2tMAYrOtqJKmHg5nvmubAKfeDA6
    Poz1ndasoRRHdxDay4Tr3WA82rdiMUxF4QG7TTcUzgm5+rYLMFdaxmlwMg==
    -----END PUBLIC KEY-----

---
apiVersion: v1
kind: Secret
metadata:
  name: "rabbitmq"
type: Opaque
stringData:
  rabbitmq-erlang-cookie: "yiBpnNKjjCokdjrVMVbSYhx4qpwom0co"
  rabbitmq-password: "qcVB6pkscGB6Ms00j2KmrMuJTzw6UigntQO2r4ymZr"

---
apiVersion: v1
kind: Secret
metadata:
  name: "deposit-service"
type: Opaque
stringData:
  bitgo-token: "yeah not leaking this one"

---
apiVersion: v1
kind: Secret
metadata:
  name: "redis"
type: Opaque
stringData:
  redis-password: "fSUqlghlkEzNqTNrJC7NuHge737qZXynEus88Z5Xsj"
