apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deposit-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "deposit-service.name" . }}
    helm.sh/chart: {{ include "deposit-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deposit-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deposit-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "BG_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecretName }}
                  key: "bitgo-token"
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redisSecret }}
                  key: "redis-password"
            - name: "RABBIT_USER"
              value: "user"
            - name: "RABBIT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitSecret }}
                  key: "rabbitmq-password"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping/
              port: 8080
          readinessProbe:
            httpGet:
              path: /ping/
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
